#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  5 18:50:52 2020

@author: Tomas
"""

# -*- coding: utf-8 -*-
"""
import scipy as 
"""
nombre = "Tomas"
dia = 3

print ("Ej 1 - Forma 1")
print ("hola Tomas es el 3 de Agosto")
print("")
print ("Ej 1 - Forma 2")
print ("hola " + nombre + " es el " + str(dia) + " de Agosto")
print("")
print ("Ej 1 - Forma 3")
print ("hola {} es el {} de Agosto".format( nombre , dia ))
print("")
print ("Ej 1 - Forma 4")
print (f"hola {nombre} es el {dia} de Agosto")

print("")
print ("Ej 2 - Forma 1")
print ("hola hola hola hola hola hola hola")
print("")
print ("Ej 2 - Forma 2")
print ("hola "*100)
